
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

import java_cup.runtime.*;
import java.util.*;
import compiler.Semantic;
import compiler.Parameter;
import compiler.VariableDecl;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintax extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\003\000\002\003" +
    "\002\000\002\003\004\000\002\004\003\000\002\004\003" +
    "\000\002\021\002\000\002\005\013\000\002\012\003\000" +
    "\002\012\003\000\002\012\003\000\002\015\002\000\002" +
    "\015\006\000\002\015\004\000\002\006\002\000\002\006" +
    "\004\000\002\007\003\000\002\007\004\000\002\007\007" +
    "\000\002\007\011\000\002\007\007\000\002\007\005\000" +
    "\002\007\003\000\002\014\002\000\002\014\003\000\002" +
    "\022\002\000\002\011\006\000\002\010\005\000\002\016" +
    "\003\000\002\016\005\000\002\016\005\000\002\016\007" +
    "\000\002\017\002\000\002\017\003\000\002\020\003\000" +
    "\002\020\005\000\002\013\005\000\002\013\005\000\002" +
    "\013\005\000\002\013\005\000\002\013\005\000\002\013" +
    "\005\000\002\013\005\000\002\013\005\000\002\013\005" +
    "\000\002\013\005\000\002\013\005\000\002\013\005\000" +
    "\002\013\006\000\002\013\003\000\002\013\003\000\002" +
    "\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\136\000\012\002\uffff\013\uffff\014\uffff\015\uffff\001" +
    "\002\000\012\002\000\013\015\014\013\015\014\001\002" +
    "\000\004\002\006\001\002\000\004\002\001\001\002\000" +
    "\012\002\ufffd\013\ufffd\014\ufffd\015\ufffd\001\002\000\004" +
    "\004\016\001\002\000\012\002\ufffe\013\ufffe\014\ufffe\015" +
    "\ufffe\001\002\000\012\002\ufffc\013\ufffc\014\ufffc\015\ufffc" +
    "\001\002\000\004\004\ufff8\001\002\000\004\004\ufff7\001" +
    "\002\000\004\004\ufff9\001\002\000\012\030\071\031\070" +
    "\035\uffe5\036\uffe5\001\002\000\006\035\021\036\020\001" +
    "\002\000\004\004\022\001\002\000\036\002\uffe6\004\uffe6" +
    "\005\uffe6\006\uffe6\007\uffe6\010\uffe6\011\uffe6\012\uffe6\013" +
    "\uffe6\014\uffe6\015\uffe6\031\uffe6\033\uffe6\034\uffe6\001\002" +
    "\000\010\030\023\035\uffe3\036\uffe3\001\002\000\012\004" +
    "\024\005\030\006\026\031\025\001\002\000\040\016\uffd0" +
    "\017\uffd0\020\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025" +
    "\uffd0\026\uffd0\027\uffd0\030\060\031\057\032\uffd0\035\uffd0" +
    "\036\uffd0\001\002\000\012\004\024\005\030\006\026\031" +
    "\025\001\002\000\034\016\uffce\017\uffce\020\uffce\021\uffce" +
    "\022\uffce\023\uffce\024\uffce\025\uffce\026\uffce\027\uffce\032" +
    "\uffce\035\uffce\036\uffce\001\002\000\032\016\035\017\031" +
    "\020\041\021\037\022\032\023\034\024\042\025\040\026" +
    "\036\027\033\035\uffe2\036\uffe2\001\002\000\034\016\uffcf" +
    "\017\uffcf\020\uffcf\021\uffcf\022\uffcf\023\uffcf\024\uffcf\025" +
    "\uffcf\026\uffcf\027\uffcf\032\uffcf\035\uffcf\036\uffcf\001\002" +
    "\000\012\004\024\005\030\006\026\031\025\001\002\000" +
    "\012\004\024\005\030\006\026\031\025\001\002\000\012" +
    "\004\024\005\030\006\026\031\025\001\002\000\012\004" +
    "\024\005\030\006\026\031\025\001\002\000\012\004\024" +
    "\005\030\006\026\031\025\001\002\000\012\004\024\005" +
    "\030\006\026\031\025\001\002\000\012\004\024\005\030" +
    "\006\026\031\025\001\002\000\012\004\024\005\030\006" +
    "\026\031\025\001\002\000\012\004\024\005\030\006\026" +
    "\031\025\001\002\000\012\004\024\005\030\006\026\031" +
    "\025\001\002\000\020\016\uffd6\017\uffd6\020\uffd6\021\uffd6" +
    "\032\uffd6\035\uffd6\036\uffd6\001\002\000\034\016\uffda\017" +
    "\uffda\020\uffda\021\uffda\022\032\023\034\024\042\025\040" +
    "\026\036\027\033\032\uffda\035\uffda\036\uffda\001\002\000" +
    "\020\016\uffd5\017\uffd5\020\uffd5\021\uffd5\032\uffd5\035\uffd5" +
    "\036\uffd5\001\002\000\034\016\uffd9\017\uffd9\020\uffd9\021" +
    "\uffd9\022\032\023\034\024\042\025\040\026\036\027\033" +
    "\032\uffd9\035\uffd9\036\uffd9\001\002\000\020\016\uffd4\017" +
    "\uffd4\020\uffd4\021\uffd4\032\uffd4\035\uffd4\036\uffd4\001\002" +
    "\000\034\016\uffdc\017\uffdc\020\041\021\037\022\032\023" +
    "\034\024\042\025\040\026\036\027\033\032\uffdc\035\uffdc" +
    "\036\uffdc\001\002\000\020\016\uffd7\017\uffd7\020\uffd7\021" +
    "\uffd7\032\uffd7\035\uffd7\036\uffd7\001\002\000\020\016\uffd3" +
    "\017\uffd3\020\uffd3\021\uffd3\032\uffd3\035\uffd3\036\uffd3\001" +
    "\002\000\020\016\uffd8\017\uffd8\020\uffd8\021\uffd8\032\uffd8" +
    "\035\uffd8\036\uffd8\001\002\000\034\016\uffdb\017\uffdb\020" +
    "\041\021\037\022\032\023\034\024\042\025\040\026\036" +
    "\027\033\032\uffdb\035\uffdb\036\uffdb\001\002\000\030\016" +
    "\035\017\031\020\041\021\037\022\032\023\034\024\042" +
    "\025\040\026\036\027\033\032\056\001\002\000\034\016" +
    "\uffd2\017\uffd2\020\uffd2\021\uffd2\022\uffd2\023\uffd2\024\uffd2" +
    "\025\uffd2\026\uffd2\027\uffd2\032\uffd2\035\uffd2\036\uffd2\001" +
    "\002\000\014\004\024\005\030\006\026\031\025\032\uffe1" +
    "\001\002\000\012\004\024\005\030\006\026\031\025\001" +
    "\002\000\034\016\035\017\031\020\041\021\037\022\032" +
    "\023\034\024\042\025\040\026\036\027\033\032\uffdd\035" +
    "\uffdd\036\uffdd\001\002\000\004\032\067\001\002\000\006" +
    "\032\uffe0\036\065\001\002\000\032\016\035\017\031\020" +
    "\041\021\037\022\032\023\034\024\042\025\040\026\036" +
    "\027\033\032\uffdf\036\uffdf\001\002\000\012\004\024\005" +
    "\030\006\026\031\025\001\002\000\032\016\035\017\031" +
    "\020\041\021\037\022\032\023\034\024\042\025\040\026" +
    "\036\027\033\032\uffde\036\uffde\001\002\000\034\016\uffd1" +
    "\017\uffd1\020\uffd1\021\uffd1\022\uffd1\023\uffd1\024\uffd1\025" +
    "\uffd1\026\uffd1\027\uffd1\032\uffd1\035\uffd1\036\uffd1\001\002" +
    "\000\014\013\015\014\013\015\014\032\ufff6\036\ufff6\001" +
    "\002\000\012\004\024\005\030\006\026\031\025\001\002" +
    "\000\032\016\035\017\031\020\041\021\037\022\032\023" +
    "\034\024\042\025\040\026\036\027\033\035\uffe4\036\uffe4" +
    "\001\002\000\006\032\077\036\076\001\002\000\004\004" +
    "\075\001\002\000\006\032\ufff4\036\ufff4\001\002\000\010" +
    "\013\015\014\013\015\014\001\002\000\004\033\100\001" +
    "\002\000\032\004\ufffb\005\ufffb\006\ufffb\007\ufffb\011\ufffb" +
    "\012\ufffb\013\ufffb\014\ufffb\015\ufffb\031\ufffb\033\ufffb\034" +
    "\ufffb\001\002\000\032\004\ufff3\005\ufff3\006\ufff3\007\ufff3" +
    "\011\ufff3\012\ufff3\013\ufff3\014\ufff3\015\ufff3\031\ufff3\033" +
    "\ufff3\034\ufff3\001\002\000\032\004\024\005\030\006\026" +
    "\007\107\011\104\012\112\013\015\014\013\015\014\031" +
    "\025\033\103\034\113\001\002\000\032\004\uffe8\005\uffe8" +
    "\006\uffe8\007\uffe8\011\uffe8\012\uffe8\013\uffe8\014\uffe8\015" +
    "\uffe8\031\uffe8\033\uffe8\034\uffe8\001\002\000\004\031\130" +
    "\001\002\000\032\004\ufff2\005\ufff2\006\ufff2\007\ufff2\011" +
    "\ufff2\012\ufff2\013\ufff2\014\ufff2\015\ufff2\031\ufff2\033\ufff2" +
    "\034\ufff2\001\002\000\034\004\uffeb\005\uffeb\006\uffeb\007" +
    "\uffeb\010\uffeb\011\uffeb\012\uffeb\013\uffeb\014\uffeb\015\uffeb" +
    "\031\uffeb\033\uffeb\034\uffeb\001\002\000\004\031\122\001" +
    "\002\000\004\004\121\001\002\000\030\016\035\017\031" +
    "\020\041\021\037\022\032\023\034\024\042\025\040\026" +
    "\036\027\033\035\120\001\002\000\014\004\024\005\030" +
    "\006\026\031\025\035\uffea\001\002\000\012\002\ufffa\013" +
    "\ufffa\014\ufffa\015\ufffa\001\002\000\034\004\ufff1\005\ufff1" +
    "\006\ufff1\007\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1\014" +
    "\ufff1\015\ufff1\031\ufff1\033\ufff1\034\ufff1\001\002\000\004" +
    "\035\117\001\002\000\030\016\035\017\031\020\041\021" +
    "\037\022\032\023\034\024\042\025\040\026\036\027\033" +
    "\035\uffe9\001\002\000\034\004\uffec\005\uffec\006\uffec\007" +
    "\uffec\010\uffec\011\uffec\012\uffec\013\uffec\014\uffec\015\uffec" +
    "\031\uffec\033\uffec\034\uffec\001\002\000\034\004\ufff0\005" +
    "\ufff0\006\ufff0\007\ufff0\010\ufff0\011\ufff0\012\ufff0\013\ufff0" +
    "\014\ufff0\015\ufff0\031\ufff0\033\ufff0\034\ufff0\001\002\000" +
    "\010\030\071\035\uffe5\036\uffe5\001\002\000\012\004\024" +
    "\005\030\006\026\031\025\001\002\000\030\016\035\017" +
    "\031\020\041\021\037\022\032\023\034\024\042\025\040" +
    "\026\036\027\033\032\124\001\002\000\030\004\024\005" +
    "\030\006\026\007\107\011\104\012\112\013\015\014\013" +
    "\015\014\031\025\033\103\001\002\000\034\004\uffef\005" +
    "\uffef\006\uffef\007\uffef\010\126\011\uffef\012\uffef\013\uffef" +
    "\014\uffef\015\uffef\031\uffef\033\uffef\034\uffef\001\002\000" +
    "\030\004\024\005\030\006\026\007\107\011\104\012\112" +
    "\013\015\014\013\015\014\031\025\033\103\001\002\000" +
    "\034\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee\011\uffee" +
    "\012\uffee\013\uffee\014\uffee\015\uffee\031\uffee\033\uffee\034" +
    "\uffee\001\002\000\012\004\024\005\030\006\026\031\025" +
    "\001\002\000\030\016\035\017\031\020\041\021\037\022" +
    "\032\023\034\024\042\025\040\026\036\027\033\032\132" +
    "\001\002\000\030\004\024\005\030\006\026\007\107\011" +
    "\104\012\112\013\015\014\013\015\014\031\025\033\103" +
    "\001\002\000\034\004\uffed\005\uffed\006\uffed\007\uffed\010" +
    "\uffed\011\uffed\012\uffed\013\uffed\014\uffed\015\uffed\031\uffed" +
    "\033\uffed\034\uffed\001\002\000\032\004\ufff3\005\ufff3\006" +
    "\ufff3\007\ufff3\011\ufff3\012\ufff3\013\ufff3\014\ufff3\015\ufff3" +
    "\031\ufff3\033\ufff3\034\ufff3\001\002\000\032\004\024\005" +
    "\030\006\026\007\107\011\104\012\112\013\015\014\013" +
    "\015\014\031\025\033\103\034\136\001\002\000\034\004" +
    "\uffe7\005\uffe7\006\uffe7\007\uffe7\010\uffe7\011\uffe7\012\uffe7" +
    "\013\uffe7\014\uffe7\015\uffe7\031\uffe7\033\uffe7\034\uffe7\001" +
    "\002\000\004\004\140\001\002\000\006\032\ufff5\036\ufff5" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\136\000\006\002\004\003\003\001\001\000\012\004" +
    "\010\005\006\010\011\012\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\016\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\026\001\001\000\002\001\001\000" +
    "\004\013\054\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\053\001\001\000\004\013" +
    "\052\001\001\000\004\013\051\001\001\000\004\013\050" +
    "\001\001\000\004\013\047\001\001\000\004\013\046\001" +
    "\001\000\004\013\045\001\001\000\004\013\044\001\001" +
    "\000\004\013\043\001\001\000\004\013\042\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\013\063\017" +
    "\061\020\062\001\001\000\004\013\060\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\065\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\012\073\015\072\001\001\000\004\013" +
    "\071\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\012\136\001\001\000" +
    "\002\001\001\000\004\021\100\001\001\000\004\006\101" +
    "\001\001\000\014\007\104\010\113\011\105\012\107\013" +
    "\110\001\001\000\004\022\133\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\016\001\001\000\002\001\001\000\006\013\115" +
    "\014\114\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\122\001\001\000" +
    "\002\001\001\000\014\007\124\010\113\011\105\012\107" +
    "\013\110\001\001\000\002\001\001\000\014\007\126\010" +
    "\113\011\105\012\107\013\110\001\001\000\002\001\001" +
    "\000\004\013\130\001\001\000\002\001\001\000\014\007" +
    "\132\010\113\011\105\012\107\013\110\001\001\000\002" +
    "\001\001\000\004\006\134\001\001\000\014\007\104\010" +
    "\113\011\105\012\107\013\110\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action_part00000000(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= unit_list 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] Iniciando parse do programa"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // unit_list ::= 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] unit_list -> empty"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("unit_list",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // unit_list ::= unit_list unit 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] unit_list -> unit_list unit"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("unit_list",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // unit ::= function 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("unit",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // unit ::= var_decl 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("unit",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$0 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int plleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		java.util.List pl = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;

                             java.util.List<Parameter> params = pl == null ? new ArrayList<Parameter>() : pl;
                             Semantic.instance.declareFunction(id, t, params);
                             Semantic.instance.enterFunction(t);
                             for (Object o : params) {
                                    Parameter p = (Parameter) o;
                                    Semantic.instance.declareVariable(p.name, p.type);
                             }
                       
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$0",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // function ::= type ID LPAREN param_list RPAREN LBRACE NT$0 stmt_list RBRACE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)).value;
		int plleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).right;
		java.util.List pl = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)).value;
		 Semantic.instance.exitFunction(); System.out.println("[Sintax] function end"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("function",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type ::= INT 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("type",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type ::= FLOAT 
            {
              String RESULT =null;
		 RESULT = "float"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("type",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // type ::= VOID 
            {
              String RESULT =null;
		 RESULT = "void"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("type",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // param_list ::= 
            {
              java.util.List RESULT =null;
		 RESULT = new ArrayList(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("param_list",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // param_list ::= param_list COMMA type ID 
            {
              java.util.List RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		java.util.List pl = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 pl.add(new Parameter(id, t)); RESULT = pl; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("param_list",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= type ID 
            {
              java.util.List RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 ArrayList l = new ArrayList(); l.add(new Parameter(id, t)); RESULT = l; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("param_list",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt_list ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt_list",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt_list ::= stmt_list stmt 
            {
              Object RESULT =null;
		 /* noop */ 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt_list",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= var_decl 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt ::= expr SEMI 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] expr stmt"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // stmt ::= IF LPAREN expr RPAREN stmt 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] if stmt"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // stmt ::= IF LPAREN expr RPAREN stmt ELSE stmt 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] if-else stmt"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // stmt ::= WHILE LPAREN expr RPAREN stmt 
            {
              Object RESULT =null;
		 System.out.println("[Sintax] while stmt"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // stmt ::= RETURN expr_opt SEMI 
            {
              Object RESULT =null;
		int eoleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eoright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String eo = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
                     String retType = Semantic.instance.currentFunctionReturnType();
                     if (eo == null) {
                            if (retType != null && !"void".equals(retType)) Semantic.instance.error("Missing return value for function expecting " + retType);
                     } else {
                            String exprType = (String) eo;
                            if (retType != null && !Semantic.instance.isCompatible(retType, exprType))
                                   Semantic.instance.error("Return type mismatch: expected " + retType + " got " + exprType);
                     }
                     System.out.println("[Sintax] return stmt");
               
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // stmt ::= block 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("stmt",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr_opt ::= 
            {
              String RESULT =null;
		 RESULT = null; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr_opt",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr_opt ::= expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = e; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr_opt",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$1 ::= 
            {
              Object RESULT =null;
 Semantic.instance.enterScope(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("NT$1",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // block ::= LBRACE NT$1 stmt_list RBRACE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		 Semantic.instance.exitScope(); System.out.println("[Sintax] block"); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("block",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // var_decl ::= type id_init_list SEMI 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int illeft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int ilright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		java.util.List il = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
                      for (Object od : (java.util.List) il) {
                             VariableDecl vd = (VariableDecl) od;
                             Semantic.instance.declareVariable(vd.name, t);
                             if (vd.hasInit) {
                                    String initType = vd.initType;
                                    if (initType != null && !Semantic.instance.isCompatible(t, initType)) {
                                           Semantic.instance.error("Type mismatch in initialization of variable " + vd.name + ": expected " + t + " got " + initType);
                                    }
                             }
                      }
                      System.out.println("[Sintax] var_decl");
                 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("var_decl",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // id_init_list ::= ID 
            {
              java.util.List RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 java.util.List l = new ArrayList(); l.add(new VariableDecl(id, null, false)); RESULT = l; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("id_init_list",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // id_init_list ::= ID ASSIGN expr 
            {
              java.util.List RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 java.util.List l = new ArrayList(); l.add(new VariableDecl(id, (String)e, true)); RESULT = l; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("id_init_list",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // id_init_list ::= id_init_list COMMA ID 
            {
              java.util.List RESULT =null;
		int illeft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int ilright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		java.util.List il = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 il.add(new VariableDecl(id, null, false)); RESULT = il; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("id_init_list",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // id_init_list ::= id_init_list COMMA ID ASSIGN expr 
            {
              java.util.List RESULT =null;
		int illeft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).left;
		int ilright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).right;
		java.util.List il = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 il.add(new VariableDecl(id, (String)e, true)); RESULT = il; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("id_init_list",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // args ::= 
            {
              java.util.List RESULT =null;
		 RESULT = new ArrayList(); 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("args",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // args ::= arg_list 
            {
              java.util.List RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int alright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		java.util.List al = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 RESULT = al; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("args",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // arg_list ::= expr 
            {
              java.util.List RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 java.util.List l = new ArrayList(); l.add(e); RESULT = l; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("arg_list",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // arg_list ::= arg_list COMMA expr 
            {
              java.util.List RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int alright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		java.util.List al = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 al.add(e); RESULT = al; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("arg_list",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= ID ASSIGN expr 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 Semantic.instance.checkAssignment(id, (String)e); RESULT = e; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr PLUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String t = Semantic.instance.arithmeticType((String)e1, (String)e2); if (t==null) Semantic.instance.error("Invalid operands for +"); RESULT = t; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= expr MINUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String t = Semantic.instance.arithmeticType((String)e1, (String)e2); if (t==null) Semantic.instance.error("Invalid operands for -"); RESULT = t; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr MUL expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String t = Semantic.instance.arithmeticType((String)e1, (String)e2); if (t==null) Semantic.instance.error("Invalid operands for *"); RESULT = t; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr DIV expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String t = Semantic.instance.arithmeticType((String)e1, (String)e2); if (t==null) Semantic.instance.error("Invalid operands for /"); RESULT = t; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr EQEQ expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String tt = Semantic.instance.arithmeticType((String)e1, (String)e2); if (tt==null) Semantic.instance.error("Invalid operands for =="); RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr NEQ expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String tt = Semantic.instance.arithmeticType((String)e1, (String)e2); if (tt==null) Semantic.instance.error("Invalid operands for !="); RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr LT expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String tt = Semantic.instance.arithmeticType((String)e1, (String)e2); if (tt==null) Semantic.instance.error("Invalid operands for <"); RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr GT expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String tt = Semantic.instance.arithmeticType((String)e1, (String)e2); if (tt==null) Semantic.instance.error("Invalid operands for >"); RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr LE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String tt = Semantic.instance.arithmeticType((String)e1, (String)e2); if (tt==null) Semantic.instance.error("Invalid operands for <="); RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr GE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String tt = Semantic.instance.arithmeticType((String)e1, (String)e2); if (tt==null) Semantic.instance.error("Invalid operands for >="); RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= LPAREN expr RPAREN 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		 RESULT = e; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= ID LPAREN args RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		java.util.List a = (java.util.List)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		
                     java.util.List argtypes = a == null ? new ArrayList() : a;
                     Semantic.FunctionInfo fi = Semantic.instance.lookupFunction(id);
                     if (fi == null) {
                            Semantic.instance.error("Call to undefined function: " + id);
                            RESULT = "int";
                     } else {
                            if (fi.paramTypes.size() != argtypes.size()) {
                                   Semantic.instance.error("Argument count mismatch in call to " + id + ": expected " + fi.paramTypes.size() + " got " + argtypes.size());
                            } else {
                                   for (int i=0;i<fi.paramTypes.size() && i<argtypes.size(); i++) {
                                          String expect = fi.paramTypes.get(i);
                                          String got = (String) argtypes.get(i);
                                          if (!Semantic.instance.isCompatible(expect, got)) {
                                                 Semantic.instance.error("Argument type mismatch in call to " + id + " at position " + (i+1) + ": expected " + expect + " got " + got);
                                          }
                                   }
                            }
                            RESULT = fi.returnType;
                     }
               
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintax$stack.peek()).value;
		 String t = Semantic.instance.lookupVariable(id); if (t==null) { Semantic.instance.error("Use of undeclared variable: " + id); RESULT = "int"; } else RESULT = t; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= INT_CONST 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= FLOAT_CONST 
            {
              String RESULT =null;
		 RESULT = "float"; 
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintax$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
              return CUP$Sintax$do_action_part00000000(
                               CUP$Sintax$act_num,
                               CUP$Sintax$parser,
                               CUP$Sintax$stack,
                               CUP$Sintax$top);
    }
}

}
