
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 18;
  public static final int ELSE = 6;
  public static final int PLUS = 12;
  public static final int RBRACE = 26;
  public static final int RPAREN = 24;
  public static final int INT = 9;
  public static final int SEMI = 27;
  public static final int WHILE = 7;
  public static final int RETURN = 8;
  public static final int IF = 5;
  public static final int LBRACE = 25;
  public static final int LPAREN = 23;
  public static final int GT = 19;
  public static final int LE = 20;
  public static final int ID = 2;
  public static final int INT_CONST = 3;
  public static final int COMMA = 28;
  public static final int FLOAT = 10;
  public static final int EOF = 0;
  public static final int DIV = 15;
  public static final int GE = 21;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int FLOAT_CONST = 4;
  public static final int ASSIGN = 22;
  public static final int EQEQ = 16;
  public static final int NEQ = 17;
  public static final int MUL = 14;
  public static final int VOID = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "INT",
  "FLOAT",
  "VOID",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "EQEQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "ASSIGN",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COMMA"
  };
}

